### ISSUE TITLE
Every upgrade of the Mac version will invalidate the word retrieval hotkey

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1046]
**Mac版安装问题**

Mac版每次覆盖安装后，取词热键就失效，必须重新在“辅助功能”里删除并重新加入，才能恢复取词热键。

Macos 12

<img width="678" alt="截屏2023-08-06 13 15 40" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/213dfb29-c3d2-4284-892e-891bd6a0817d">

**Comment by shenlebantongying** [comment]
The problem is that we don't/won't pay Apple 99$ per year to have a Developer account to sign the `GoldenDict.app`, so macOS consider every `GoldenDict.app` to be distributed by a different vendor. So, the permission again has to be granted again for every new `GoldenDict.app`.

https://github.com/xiaoyifang/goldendict-ng/blob/1ee42bd59982105596c2b40997d42cd60e8f8573/.github/workflows/macos-homebrew.yml#L126

**Comment by yshumy** [comment]
> The problem is that we don't/won't pay Apple 99$ per year to have a Developer account to sign the `GoldenDict.app`, so macOS consider every `GoldenDict.app` to be distributed by a different vendor. So, permission has to be granted again for every new `GoldenDict.app`.问题是我们不会/不会每年向Apple 支付 99 美元来拥有一个开发人员帐户来签署 `GoldenDict.app` ，因此 macOS 认为每个都 `GoldenDict.app` 由不同的供应商分发。因此，必须为每个新的 `GoldenDict.app` .
> 
> https://github.com/xiaoyifang/goldendict-ng/blob/1ee42bd59982105596c2b40997d42cd60e8f8573/.github/workflows/macos-homebrew.yml#L126

可以在版本说明中提到这个操作。

**Comment by shenlebantongying** [comment]
Pay Apple $99 per year seems unlikely.
