### ISSUE TITLE
xkbcommon error (Flatpak only)

### ISSUE THREAD

**Issue by yue-dongchen** [xiaoyifang/goldendict-ng#1348]
**Describe the bug**
Program does not start, pointing to the XKB layout that I defined myself. Repo: https://github.com/yue-dongchen/QSfNQL/tree/main/Latin/neo/Linux%20(XKB)

I have not tested X11 but this issue should be Wayland-only, since X11 does not use `libxkbcommon`. Works fine with the APT version.

**To Reproduce**
1. Install Flatpak 23.12.23
2. Apply my XKB layout by appending the configuration extracts to `/usr/share/X11/xkb/...`, and enabling them in whatever settings utility.
3. Launch Goldendict-NG
```
qt.qpa.qgnomeplatform: Could not find color scheme  ""
Qt: Session management error: Could not open network socket
xkbcommon: ERROR: Couldn't process include statement for 'de(neo_qsfnql)'
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
[2:29:0101/195947.738273:FATAL:xkb_keyboard_layout_engine.cc(651)] Keymap file failed to load: de-neo_qsfnql
```

**OS and software versions**

Copy & paste `help` -> `about` -> `Copy version info` to here

- OS: Ubuntu 23.10 with GNOME 45.1

**Comment by shenlebantongying** [comment]
The problem is that the sandbox created by Flatpak does not reuse system's `/usr/share/X11/xkb/...`

This can be confirmed by entering the sandbox's shell
```sh
$ flatpak run --command=sh io.github.xiaoyifang.goldendict_ng
$ cd /usr/share/X11/xkb/ #  -> is not the system's /usr/share/X11/xkb/
```

libxkbcommon is part of `org.freedesktop.Platform`

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/libxkbcommon.bst

I don't know how to modify runtime's `/usr`, which appears to be special.

However, libxkbcommon does load files from `$XDG_CONFIG_HOME/xkb/`
https://xkbcommon.org/doc/current/md_doc_2user-configuration.html

And inside flatpak the `$XDG_CONFIG_HOME/xkb/` is
```sh
$ flatpak run --command=sh io.github.xiaoyifang.goldendict_ng
$ echo "$XDG_CONFIG_HOME/xkb"

/home/slbtty/.var/app/io.github.xiaoyifang.goldendict_ng/config/xkb
```

You can create the xkb fileson `~/.var/app/io.github.xiaoyifang.goldendict_ng/config/` (if you installed the app to the user.). This can be done both inside and outside of the sandbox.

> enabling them in whatever settings utility.

I don't know what you use, but if it reuses underlying libxkbcommon, it should load from `$XDG_CONFIG_HOME/xkb/`

**Comment by yue-dongchen** [comment]
谢谢。我明天试试。新年快乐

**Comment by shenlebantongying** [comment]
I don't know what we need to do, flatpak is a sandbox which is different from normal OS.

Modifying as above comment should work. Reopen if it doesn't.
