### ISSUE TITLE
Please provide more information on the various builds

### ISSUE THREAD

**Issue by gumbolastima** [xiaoyifang/goldendict-ng#1391]
It is not clear in the releases what each  build is for. For example, what is the " 6.6.1-GoldenDict_flyci-macos-large-latest-m2_homebrew_{date}.dmg " build and how does it differ from the other macOS builds?

Please add in some kind of explanation. Thank you!

**Comment by xiaoyifang** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/105986/96b79532-1b88-40ef-a6c6-9c60c28c76a9)

**Comment by AnLuoRidge** [comment]
For `6.6.1-GoldenDict_flyci-macos-large-latest-m2_homebrew_20240122.dmg`

- flyci means [FlyCI](https://www.flyci.net)
- large-latest. I reckon this is the CI runner spec.
- m2 is the M2 runner. However, M2 only makes sense to the developer. It confuses the user, because model of the chip is not relevant to the dmg. I'd recommend using "arm" instead.
- homebrew. I don't understand. GoldenDict-ng is not on homebrew.

**Comment by shenlebantongying** [comment]
> homebrew. I don't understand this. GoldenDict-ng is not on homebrew.

Well, in the past, we used to build dependencies by ourselves. Then, we just pull them from homebrew, thus homebrew 😅

Anyway, I deleted most of them now.
