### ISSUE TITLE
adjust icon size

### ISSUE THREAD

**Issue by KonstantinDjairo** [xiaoyifang/goldendict-ng#1449]
is there any way to adjust the size of the dictionary icons, to make them a bigger ? 
![image](https://github.com/xiaoyifang/goldendict-ng/assets/53496273/e8709552-bb62-4db8-a1a1-f0a07fafb69a)

**Comment by shenlebantongying** [comment]
As of now, No.

It is hard-coded into `QStyle::PM_ToolBarIconSize`

https://github.com/xiaoyifang/goldendict-ng/blob/46fc6a9889d4b1255670df682dcf3df7e86b6038/src/ui/mainwindow.cc#L1674-L1678

Also, it appears that qt's toolbar buttons' icon won't scale up by design :sweat_smile: 

https://doc.qt.io/qt-6/qtoolbutton.html#details
https://doc.qt.io/qt-6/qmainwindow.html#iconSize-prop
https://doc.qt.io/qt-6/qabstractbutton.html#iconSize-prop

**Comment by KonstantinDjairo** [comment]
that's unfortunate , it'd be cool to have a dynamic value instead of a hard-coded one

**Comment by shenlebantongying** [comment]
I think we should enhance old features to cover this case. https://github.com/xiaoyifang/goldendict-ng/issues/1459
