### ISSUE TITLE
Dark reader mode: welcome page's text also get dark when turning on.

### ISSUE THREAD

**Issue by atauzki** [xiaoyifang/goldendict-ng#1450]
The version I used is compiled with qt6.7.0: 
https://cloud.freemdict.com/index.php/s/psF3GZstsYZ3JZc

step:
1. open goldendict
2. set "Dark reader mode" to "ON"
3. text are getting black.

This is the screenshort:
https://github.com/xiaoyifang/goldendict-ng/assets/19769843/26695d63-5a8d-4855-9d90-96970d2b8927

**Comment by atauzki** [comment]
And I also tried the version on Github, it takes no effect before relaunching the program.

**Comment by shenlebantongying** [comment]
I don't have time right now due to exams in the following weeks.

However, these are my guesses:

1. This change is problematic https://github.com/xiaoyifang/goldendict-ng/pull/1406
2. Various code were added to Qt6.7 that enables Chrome's built-in dark mode. Qt6.7 has this new [ForceDarkMode](https://github.com/qt/qtwebengine/blob/ac447e8dc2f0b0c711ca17211646784dc9c5395f/src/core/doc/src/qwebenginesettings_lgpl.qdoc#L180-L182) is added to uses Chrome's built-in dark mode (which is an exp
experimental feature flag chrome://flags/#enable-force-dark)
3. We need to bump `dark-reader.js` which is almost 2 years behind
    1. https://github.com/xiaoyifang/goldendict-ng/blob/staged/src/scripts/darkreader.js
    1. https://github.com/darkreader/darkreader/blob/main/CHANGELOG.md#4958-sep-22-2022

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/pull/1452

@atauzki  can you help to try this PR?

**Comment by atauzki** [comment]
background and text in welcome bage dont change.

**Comment by xiaoyifang** [comment]
I guess the reason is that the welcome page does not refresh when the dark mode setting changes

**Comment by atauzki** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/19769843/bb338bf7-d785-4d58-9475-5e625f8f0d9f)
compiled last code, and comment these code, still reproducable.

**Comment by shenlebantongying** [comment]
Don't screenshot code my friend, just copy and paste 🫠🫠🫠🫠🫠

**Comment by shenlebantongying** [comment]
I still cannot reproduce, the article-style.css is inserted.

Maybe a bug of re-release Qt6.7? This issue was opened when Qt6.7 was not yet released.

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/05396e9e-2044-4df1-a9b0-138d2ca40f99)

**Comment by atauzki** [comment]
I tried 6.6.x build on Mar 31. It qt6.6.2 based, and qt 6.7.0 action is not completed that time.

**Comment by xiaoyifang** [comment]
I remembered that the Welcome page is used page->setHtml() while other pages use page->loadUrl(),
maybe this is the reason

**Comment by shenlebantongying** [comment]
There is nothing wrong with darkreader mode here. The initial issue is not reproducible and it maybe simply a bug of prerelease Qt.

The only problem is that the welcome page isn't refreshed with other pages when config changed because the existance of welcome tab is different. This isn't a serious bug.

**Comment by xiaoyifang** [comment]
It can be reproduced .
