### ISSUE TITLE
Windows, CMake CMAKE_TOOLCHAIN_FILE should not be set?

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#1681]
https://github.com/xiaoyifang/goldendict-ng/blob/1fcc73ea5d6fb8c706eab0ab32d8331f84ac6a23/.github/workflows/release-windows-vcpkg-cmake.yml#L131

when set the value ,the vcpkg cache will not be used.

https://github.com/xiaoyifang/goldendict-ng/blob/1fcc73ea5d6fb8c706eab0ab32d8331f84ac6a23/CMakeLists.txt#L26-L39

**Comment by shenlebantongying** [comment]
The release build currently uses GitHub caches `VCPKG_BINARY_SOURCES -> x-gha`.

This one works, but not sure why it doesn't always work. (because GitHub redeploying their windows image every week which also bumps vcpkg version to the current HEAD?)

<img width="400" src="https://github.com/user-attachments/assets/e366de79-fdf0-48ef-b4b5-6bbe5dc30872">

https://github.com/xiaoyifang/goldendict-ng/blob/9d4bb50f2019994471ca8535c72c1b9809284fab/.github/workflows/release-windows-vcpkg-cmake.yml#L109-L118

**Comment by xiaoyifang** [comment]
> The release build currently uses GitHub caches `VCPKG_BINARY_SOURCES -> x-gha`.

NO need to use github cache ,as vcpkg packages do not need compile again.

**Comment by xiaoyifang** [comment]
![image](https://github.com/user-attachments/assets/e16062b0-ea82-4327-8438-a04e7a7e0d20)

**Comment by xiaoyifang** [comment]
![image](https://github.com/user-attachments/assets/6e8e0171-a385-46d0-a252-790c93be18f1)
