### ISSUE TITLE
[Feature] Improve changelog generation

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#1684]
gd-ng use `mikepenz/release-changelog-builder-action@v3` to generate the changelog, it has generated some unintended content.

![image](https://github.com/user-attachments/assets/623f3922-fd66-47a4-89d5-c0696e635ca1)

maybe related with some wrong configuration .

need a better way to generate this .

**Comment by KonstantinDjairo** [comment]
isn't there a way to use regex to get rid of unwanted info?

**Comment by xiaoyifang** [comment]
the changelog based on the result of `git diff   commit1..commit2 `
the result of git diff seems give out different results when the default merged branch is different.

**Comment by shenlebantongying** [comment]
With https://github.com/xiaoyifang/goldendict-ng/pull/1836, we can just manually trigger the build from the default branch instead of merging it to `dev`.

I guess this can be counted as fixed. (For release build, let's consider it before next release. Or we simply don't consider at all, because it don't happen frequently, manually editing the note is just fine 😅.)
