### ISSUE TITLE
latest release lacks qt6.7.2 files

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#1777]
latest release lacks qt6.7.2 files
![image](https://github.com/user-attachments/assets/ba93e275-f7fd-43e0-8198-52d1039ed8c2)

**Comment by xiaoyifang** [comment]
@shenlebantongying  can you have a look in the master branch?

**Comment by shenlebantongying** [comment]
I triggered the workflow again https://github.com/xiaoyifang/goldendict-ng/actions/runs/10849595625

Not sure why, the macOS build also failed mythically 2 days ago, also fixed by rerun the workflow :sweat_smile:  https://github.com/xiaoyifang/goldendict-ng/actions/runs/10849595636/job/30109125711#step:8:106

**Comment by shenlebantongying** [comment]
BTW, you need to click the "show all" to see it :sweat_smile:  
![image](https://github.com/user-attachments/assets/90bc48f1-e81d-4c52-98d9-c84f39cf2bfb)
