### ISSUE TITLE
Qt: Session management error: None of the authentication protocols specified are supported

### ISSUE THREAD

**Issue by GD-fix** [xiaoyifang/goldendict-ng#1779]
**Describe the bug**
Doesn't run with error: `Qt: Session management error: None of the authentication protocols specified are supported`

**To Reproduce**
1. Command prompt: `flatpak run io.github.xiaoyifang.goldendict_ng`
2. If GD-ng runs, exit it and do 1 the second time
3. See error

**Expected behavior**
That it works not only at first run.

**OS and software versions**

- OS: OpenSUSE Tumbleweed
- Version up to date

**Comment by GD-fix** [comment]
After OS reboot it was run, but with the same error...

**Comment by xiaoyifang** [comment]
https://github.com/flameshot-org/flameshot/issues/3115

**Comment by GD-fix** [comment]
`unset SESSION_MANAGER` command execution prevents the "`Qt: Session management error: None of the authentication protocols specified are supported`" appearance, but it doesn't solve the main problem: **I can't rerun the application without restarting the OS**.
With mentioned rpm version there isn't such problem...

**Comment by xiaoyifang** [comment]
maybe a flatpak issue

**Comment by GD-fix** [comment]
If the GD-ng developer had replaced the GD-ng normally binary releases by the Flatpak one (without the GD-ng users request), the author of such "flatpak issue" must be the GD-ng developer. Am I right?

**Comment by shenlebantongying** [comment]
No, you are wrong.

If you wonder who is responsible, it is you, actually.

Your own wellbeing and happiness is your own problem.

You can use the product for “free” doesn't mean someone else suddenly to have responsibility to fix your issues.

> without the GD-ng users request

I helped to make GD available in a few ways (flatpak + a few linux distros) because I want us and original GD's author/maintainers and various others people's effort to be more useful, and it is not for you. Your opinion is absolutely not my concern at all.

The “static” binary doesn't work, it simply crashes for random reasons because everyone's Linux distros and configurations are different. I won't do it, because the experience is super bad.

If you want the best experience, why don't you “simply” build binary releases or “simply” learn to use RPM and update the package in openSUSE's factory.

---

I just close this because googling `"Flatpak" Qt: Session management error` shows there are similar issues recently and root issue have not been found.

Feel free to open a new issue if you or someone else figured out what to fix.

> I can't rerun the application without restarting the OS.

It is likely GD is not quitted yet. Run `flatpak ps` will list it, and you can `flatpak kill` it. No idea why, maybe GD's tray icon is still there.
