### ISSUE TITLE
Extension of Auto group feature with custom user-defined groups defined via short codes after file name?

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#483]
### Discussed in https://github.com/xiaoyifang/goldendict/discussions/472

<div type='discussions-op-text'>

<sup>Originally posted by **michaelbeijer** April 12, 2023</sup>
 It would be very cool if you could extend the very useful **Auto groups** feature, so that things other than language codes (nl-en, nld-eng, etc.) could be used to automatically create groups. For example, I am currently trying to devise a system to organise all my glossaries inside GoldenDict, where I am using language codes and language pairs, such as nl-en, en-nl, nl-nl, etc. However, I would also like to use a few other groups based on stuff like whether the glossary is an abbreviations resource (‘abbrev’), my own work (‘beijer’), from a specific publisher (‘oxford’), etc. 

It would be amazing if the user could add short, custom codes behind the file name that GoldenDict could use to auto-group them.

For example, I could imagine a file naming scheme such as:

Acronyms_used_in_the_CISA_Exam **(en-en, abbrev)**.dsl
Acronyms_used_in_the_CISA_Exam **[en-en, abbrev]**.dsl
Acronyms_used_in_the_CISA_Exam **{en-en, abbrev}**.dsl

… where the various automatic groups were contained in special brackets after the file name, and separated by commas.</div>

**Comment by shenlebantongying** [comment]
I think `Auto group by Folder` is more reasonable than `Auto group by some eppended text after dictionary file names`.

Formats like MDX & stardict usually has multiple files, and renaming them requires a user to know some tricks to mass appending file names. Also, this requires documentation that no one want to read.

`Auto group by Folder` is reusing file system's existing hierarchy rather than reinventing wheels.

How about we reuse this interface?
<img src="https://user-images.githubusercontent.com/20123683/231936119-f4ef9ea1-ac97-45b2-b303-0536c5488ac4.png" width=300>

With those paths, if the user press "Auto group by folders", 4 groups will occur.

**Comment by xiaoyifang** [comment]
based on foldername is an option.
or based on an extra file such as metadata.txt with the content like this
```
category: one, two,three.
```

**Comment by michaelbeijer** [comment]
> based on foldername is an option. or based on an extra file such as metadata.txt with the content like this
> 
> ```
> category: one, two,three.
> ```
> 
> metadata.txt can also be used for other extended functions such as , set a custom dictionary name such as `title: "new title"`

Ideally, you would give the user **both** options: 
1. based on folder name
2. based on some kind of metadata.txt file (placed in the same folder as the dictionary), which could be used for all kinds of cool stuff, and even be built into a **full-fledged tagging system**, which would be very cool as you could them group two dictionaries from different folders, based on a shared tag (something which is currently impossible, as well as impossible if you base the system only on folders)

**Comment by xiaoyifang** [comment]
folder group,how many group should be created based on the following structure
```mermaid
A->B
B->C
C->D
D->E1
D->E2
B->F1
C->G2

```
ABCD is folder

**Comment by shenlebantongying** [comment]
3 

D with E1 & E2
C with G2
B with F1

Why?

Because we cannot know how deep should we should go backward based on a dict's main dict :sweat_smile: 

---

I have though about 3 possible designs based on folders:

There are multiple designs in my mind, not sure which one is the most intuitive one:

#### 1. Based on Sources ⇾ Files

One path is equal to one group.

Pros: Flexible. User may add any path they want.

Cons: Need to add every path/groups manually.

Altertnative 1.

In the group tab: "Add Folder as group" -> Scan all dicts under the folder and put them as group

Cons: Still require manual path adding, and cannot migrate dict folder to another machine without redo this process.


#### 2. Based on shared root Folders

Or "Auto Group by Containing folder"

If the two or more dictionaries share a Root folder, then they belong to the same group

```
Folder1
  |-- DictA/
  |-- DictB/
Folder2
  |-- DictA/
  |-- DictC/

````

Pros: Easy, just move files.

Cons: Nested folder structure is werid:

Should DictE belong to Folder2 or Folder3?

```
Folder1
  |-- DictA/
  |-- DictB/
Folder2
  |-- DictC/
  |-- DictD/
  |-- Folder3
        |-- DictE/
```

Personally, I think this is the best.

The DictE will be part of Folder3. If a user spot the anomitiy, he will understand there only the direct containing folder of a Dict matters. Then he will move the Folder3 out of Folder2. (Pure guessing, not sure if everyone think this way :sweat_smile: )

#### 3. Based on an anchor root folder

Ask to select one folder as anchor/Mainfolder, then all direct subfolders is a group.

```
MainFolder
  |-- Folder1
  |    |-- DictA/
  |    |-- DictB/
  |-- Folder2
       |-- DictA/
       |-- DictC/
```

Cons: Less heuristic and require all files under single folder.

Someone designed this way:

```
MainFolder
  |-- .gdAutoGroup # <- this file says this folder is used to autogroup
  |-- Folder1

MainFolder2
  |-- .gdAutoGroup # <- this file says this folder is used to autogroup
  |-- Folder2
```

Cons: Require user to read doc to know how it works. Nobody read doc.

**Comment by xiaoyifang** [comment]
2 is more realistic

For 1 ,3 users must enable recursive scan
