### ISSUE TITLE
The binary's name should be changed

### ISSUE THREAD

**Issue by data-man** [xiaoyifang/goldendict-ng#690]
To avoid conflict with the original GD.

E.g. to `goldendict-ng`.

**Comment by shenlebantongying** [comment]
Changing the binary name `/usr/bin/goldendict` on linux will break someone's scripts.

https://github.com/search?q=goldendict+language%3AShell&type=code

It should not be changed on linux, but the display name of the desktop file can be changed.

https://github.com/xiaoyifang/goldendict-ng/blob/fc4f782f28f0168a03f5d8f05d941dda95dc3de2/redist/org.goldendict.GoldenDict.desktop#L5-L9

**Comment by shenlebantongying** [comment]
> Many Linux distros has goldendict package

This is no longer the reality, only a few distros have it :)

https://repology.org/project/goldendict/versions (a few of them is this repo but without name change).

debian has both goldendict & goldendict-webengine, and it works ok.

Also, longer name need more types when using command line.

I might be wrong, but I feel this is a breaking change for Linux users if they already use this repo.

**Comment by data-man** [comment]
> debian has both goldendict & goldendict-webengine, and it works ok.

No.

`$ sudo apt install goldendict goldendict-webengine`

> The following packages have unmet dependencies:
> goldendict-webengine : Breaks: goldendict

> is a breaking change for Linux users

That's the way! :)

**Comment by xiaoyifang** [comment]
Maybe need some more time to think a better idea.

**Comment by xiaoyifang** [comment]
https://tecadmin.net/linux-update-alternatives-command/

**Comment by shenlebantongying** [comment]
Binary name is not the only thing that conflict.

There are also icons and other resources.

---

The `/usr/share/pixmaps/goldendict.png` cannot be changed, because some icons theme does provides custom goldendict icon, if we change the icon name, we breaks :sweat_smile: 

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/16x16/apps/goldendict.svg

https://github.com/daniruiz/flat-remix/blob/master/Flat-Remix-Red-Dark/apps/scalable/goldendict.svg

**Comment by shenlebantongying** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2213078#c13

What do you think @xiaoyifang ?

I think renaming the binary is breaking the change to existing users.

Anyway, we can create a compile-time flag that renames things.
