### ISSUE TITLE
Can it natively support the ARM chip on macOS?

### ISSUE THREAD

**Issue by liuchanghuaX1** [xiaoyifang/goldendict-ng#842]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xiaoyifang** [comment]
等到github支持的时候，就考虑支持。

**Comment by cosmic-latte** [comment]
GitHub has announced on 2 October that the Apple Silicon (M1) based macOS runner is now in public beta. 
actions/runner-images#8439
So is it now possible to provide a native build against Apple Silicon?

**Comment by xiaoyifang** [comment]
seems it is offered for a fee

**Comment by cosmic-latte** [comment]
Have you considered accepting donations through public channels?

**Comment by xiaoyifang** [comment]
Not in plan.

**Comment by radeva** [comment]
Hi @xiaoyifang ,

Feel free to use [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's **AND** we have a free tier for OSS projects (see below).

# Install Instructions

1. Install [FlyCI app](https://github.com/apps/flyci-prod) and 
2. Easily replace one one and start using FlyCI runners:

```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```
# 500 mins/month Free for Public Repos

Since your repo is public, FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner for public projects. 

Don't hasitate to contact us in case the free tier doesn't suit your needs or you experience any issues with the runners. Our team is here to support you!

Best Regards,
Veselina Radeva
Product Manager at [FlyCI](https://flyci.net/)

**Comment by xiaoyifang** [comment]
Thanks very much.   I'll see what I can do .

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.12.08-alpha.bae121b7

This is the release built with FlyCI  ,can someone check whether it can work normally?

**Comment by xiaoyifang** [comment]
it can work on mac14 .

closed.

**Comment by ElhemEnohpi** [comment]
Github now has M1 runners with macOS 14, free:

[GitHub Actions: Introducing the new M1 macOS runner available to open source! - The GitHub Blog](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)
