### ISSUE TITLE
[feature]command line option --show-info

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#867]
**Is your feature request related to a problem? Please describe.**
add some extra options to commandline like 
```
--show-info ,display configuration folder etc.
--version , show  version etc.

```

**Comment by shenlebantongying** [comment]
`-v, --version` is more standard-ish. We don't need two flags for almost the same thing. Just `--version` and print everything.

Maybe we should also print info to stdout so that if someone attaches a log, it will automatically include version info. For example, python prints version info:

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/8e80f351-3863-437c-91e1-f16b8d5ba423)
